name: Release Workflow

on:
  push:
    branches:
      - main

jobs:

  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Restore Dependencies
      run: dotnet restore Localisation/Localisation.csproj

    - name: Build Application x64
      run: dotnet publish --configuration Release --runtime win-x64 --output ./artifacts/x64/MyApp Localisation/Localisation.csproj

    - name: Build Application x86
      run: dotnet publish --configuration Release --runtime win-x86 --output ./artifacts/x86/MyApp Localisation/Localisation.csproj

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app_artifacts
        path: ./artifacts

  create_release:
    needs: build_and_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUBTOKEN }}
        script: |
          const { data } = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v1.0.0',
            name: 'Release v1.0.0',
            draft: false,
            prerelease: false,
          });
          core.setOutput('upload_url', data.upload_url);

  upload_release:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: app_artifacts

    - name: Upload x64 Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./app_artifacts/x64/MyApp/MyApp.exe
        asset_name: MyApp_x64.exe
        asset_content_type: application/vnd.microsoft.portable-executable

    - name: Upload x86 Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./app_artifacts/x86/MyApp/MyApp.exe
        asset_name: MyApp_x86.exe
        asset_content_type: application/vnd.microsoft.portable-executable

  cleanup:
    needs: [upload_release]
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup
      run: rm -rf ./artifacts
