name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: "gani-23/DynamicLocalisation"
        ref: main

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x' # .NET 6.0 version

    - name: Restore Dependencies
      run: dotnet restore Localisation/Localisation.csproj

    - name: Build Application x64
      run: dotnet build --configuration Release --runtime win-x64 --output ./releases/x64 Localisation/Localisation.csproj

    - name: Build Application x86
      run: dotnet build --configuration Release --runtime win-x86 --output ./releases/x86 Localisation/Localisation.csproj

    - name: Publish Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app_release
        path: ./releases

  create_release:
    needs: build_and_release
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        tag_name: v1.0.0 # You can dynamically set this based on versioning
        release_name: Release v1.0.0 # You can dynamically set this based on versioning
        draft: false
        prerelease: false

  upload_release:
    needs: create_release
    runs-on: ubuntu-latest

    steps:
    - name: Upload Release Artifact
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releases
        asset_name: app_release.zip
        asset_content_type: application/zip

  cleanup:
    runs-on: ubuntu-latest
    needs: upload_release
    steps:
    - name: Cleanup
      run: rm -rf ./releases
