name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: "YourGitHubUsername/DynamicLocalisation"
        ref: main # or whatever your branch name is

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x' # .NET 6.0 version

    - name: Restore Dependencies
      run: dotnet restore Localisation/Localisation.csproj

    - name: Build Application
      run: dotnet build --configuration Release Localisation/Localisation.csproj

    - name: Publish Application
      run: dotnet publish -c Release -o ./releases Localisation/Localisation.csproj

    - name: Create Release Archive
      run: |
        cd releases
        zip -r app_release.zip ./*
        mv app_release.zip ../
      shell: bash

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: ./app_release.zip

    - name: Cleanup
      run: rm -rf ./releases ./app_release.zip
